import Header from './components/Header';
import Form from './components/Form';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface ReservationPageProps {
  params: {
    slug: string;
  }
  searchParams: {
    date: string;
    partySize: string;
  }
};

const fetchRestaurantBySlug = async (slug: string): Promise<{ name: string } | undefined> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      name: true
    }
  });

  if (!restaurant) {
    console.error('cannot find restaurant');
    return;
  }

  return restaurant;
}

export const metadata = {
  title: 'Reserve at Milestones Grill (Toronto)',
  description: 'Generated by create next app',
}

const ReservationPage = async ({ params, searchParams }: ReservationPageProps) => {
  const { partySize } = searchParams;
  const { slug } = params;
  const [day, time] = searchParams.date.split('T');
  const { name }= await fetchRestaurantBySlug(slug) as { name: string };
  
  return (
    <>
      <div className="border-t h-screen text-black">
        <div className="py-9 w-3/5 m-auto">
          <Header 
            day={day}
            time={time}
            partySize={partySize}
            name={name}
          />
          <Form 
            slug={slug}
            day={day}
            time={time}
            partySize={partySize}
          />
        </div>
      </div>
    </>
  )
}

export default ReservationPage;
