import Header from './components/Header'
import Form from './components/Form'

export const metadata = {
  title: 'Reserve at Milestones Grill (Toronto)',
  description: 'Generated by create next app',
}

const ReservationPage = () => {
  return (
    <>
      <div className="border-t h-screen text-black">
        <div className="py-9 w-3/5 m-auto">
          <Header />
          <Form />
        </div>
      </div>
    </>
  )
}

export default ReservationPage;