import RestaurantNavBar from '../components/RestaurantNavBar';
import Menu from '../components/Menu';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface MenuPageProps {
  params: {
    slug: string;
  }
};

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      items: true
    }
  })

  if (!restaurant) {
    throw new Error
  };

  return restaurant.items;
}

export const metadata = {
  title: 'Menu - Milestones Grill (Toronto)',
  description: 'Generated by create next app',
}

const MenuPage = async ({params}: MenuPageProps) => {
  const menu = await fetchRestaurantMenu(params.slug);

  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow text-black">
        <RestaurantNavBar slug={params.slug} />
        <Menu menu={menu}/>
      </div>          
    </>
  )
}

export default MenuPage;