import RestaurantNavBar from '../components/RestaurantNavBar';
import Menu from '../components/Menu';
import { PrismaClient } from '@prisma/client';
import { Metadata } from 'next';

const prisma = new PrismaClient();

interface MenuPageProps {
  params: {
    slug: string;
  }
};

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      items: true
    }
  })

  if (!restaurant) {
    throw new Error
  };

  return restaurant.items;
};

export const generateMetadata = async ({ params }: MenuPageProps): Promise<Metadata | undefined> => {
  const { slug } = params;
  const { name } = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      name: true
    }
  }) as { name: string};

  return {
    title: `Menu - ${name}`,
    description: 'Generated by create next app'
  };
};

const MenuPage = async ({params}: MenuPageProps) => {
  const menu = await fetchRestaurantMenu(params.slug);

  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow-md text-black">
        <RestaurantNavBar slug={params.slug} />
        <Menu menu={menu}/>
      </div>          
    </>
  )
}

export default MenuPage;