import SearchHeader from './components/Header';
import Sidebar from './components/Sidebar';
import SearchRestaurantCard from './components/RestaurantCard';

export const metadata = {
  title: 'Search Restaurants | OpenTable',
  description: 'Generated by create next app',
}

const SearchPage = () => {
  return (
    <>
      <SearchHeader />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start text-black">
        <Sidebar />
        <div className="w-5/6">
          <SearchRestaurantCard />
        </div>
      </div>
    </>
  )
}

export default SearchPage;