import SearchHeader from './components/Header';
import Sidebar from './components/Sidebar';
import SearchRestaurantCard from './components/RestaurantCard';
import { Cuisine, Location, PRICE, PrismaClient, Restaurant } from '@prisma/client';

export const metadata = {
  title: 'Search Restaurants | OpenTable',
  description: 'Generated by create next app',
}

export interface CityRestaurantType {
  id: number;
  name: string;
  main_image: string;
  price: PRICE;
  cuisine: Cuisine;
  location: Location;
  slug: string;
}

interface CityDataType {
  restaurants: CityRestaurantType[];
  cuisines: Cuisine[];
  locations: Location[];
}

interface SearchParams {
  city?: string;
  cuisine?: string;
  price?: PRICE;
}

interface WhereParams {
  location?: {
    name: {
      equals: string;
    }
  },
  cuisine?: {
    name: {
      equals: string;
    }
  },
  price?: {
    equals: PRICE;
  }
}

const prisma = new PrismaClient();

const fetchSearchData = async (searchParams: SearchParams): Promise<CityDataType> => {
  const where: WhereParams = {};

  if (searchParams.city) {
    const location = {
      name: {
        equals: searchParams.city.toLowerCase()
      }
    }
    where.location = location;
  };

  if (searchParams.cuisine) {
    const cuisine = {
      name: {
        equals: searchParams.cuisine.toLowerCase()
      }
    }
    where.cuisine = cuisine;
  };

  if (searchParams.price) {
    const price = {
      equals: searchParams.price
    }
    where.price = price;
  };

  const select = {
    id: true,
    name: true,
    main_image: true,
    price: true,
    cuisine: true,
    location: true,
    slug: true
  };

  const cuisines = await prisma.cuisine.findMany();

  const locations = await prisma.location.findMany();

  const restaurants = await prisma.restaurant.findMany({
    where,
    select
  });    

  
  return {
    restaurants,
    cuisines,
    locations
  };
};

const SearchPage = async ({searchParams}: {searchParams: SearchParams }) => {
  const data = await fetchSearchData(searchParams);
  const { restaurants, cuisines, locations} = data;

  return (
    <>
      <SearchHeader />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start text-black">
        <Sidebar cuisines={cuisines} locations={locations} searchParams={searchParams}/>
        <div className="w-5/6">
          {restaurants.length ? 
          restaurants.map((restaurant, i) => (
            <SearchRestaurantCard restaurant={restaurant} key={`restaurant.name-${i}`} /> 
          )) :
          <p>No restaurants found in <span className="capitalize">{searchParams.city}</span></p>
          }
        </div>
      </div>
    </>
  )
}

export default SearchPage;