import RestaurantNavBar from './components/RestaurantNavBar';
import Title from './components/Title';
import Rating from './components/Rating';
import Description from './components/Description';
import Images from './components/Images';
import Reviews from './components/Reviews';
import ReservationCard from './components/ReservationCard';

export const metadata = {
  title: 'Milestones Grill (Toronto) | OpenTable',
  description: 'Generated by create next app',
}

const RestaurantDetailsPage = () => {
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow text-black">
        <RestaurantNavBar />
        <Title />
        <Rating />
        <Description />
        <Images />
        <Reviews />   
      </div>
      <ReservationCard />
    </>
  )
}

export default RestaurantDetailsPage;