import RestaurantNavBar from './components/RestaurantNavBar';
import Title from './components/Title';
import Rating from './components/Rating';
import Description from './components/Description';
import Images from './components/Images';
import Reviews from './components/Reviews';
import ReservationCard from './components/ReservationCard';
import { PrismaClient, Review } from '@prisma/client';
import { notFound } from 'next/navigation';

const prisma = new PrismaClient();

interface Restaurant {
  id: number;
  name: string;
  images: string[];
  description: string;
  slug: string;
  reviews: Review[];
  open_time: string;
  close_time: string;
};

interface RestaurantDetailsPageProps {
  params: {
    slug: string;
  }
};

const fetchRestaurantBySlug = async (slug: string): Promise<Restaurant> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      id: true,
      name: true,
      images: true,
      description: true,
      slug: true,
      reviews: true,
      open_time: true,
      close_time: true
    }
  });

  if (!restaurant) {
    notFound();
  };

  return restaurant;
};

export const metadata = {
  title: 'Milestones Grill (Toronto) | OpenTable',
  description: 'Generated by create next app',
}

const RestaurantDetailsPage = async ({params}: RestaurantDetailsPageProps) => {
  const { id, name, images, description, slug, reviews, open_time, close_time } = await fetchRestaurantBySlug(params.slug);
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow text-black">
        <RestaurantNavBar slug={slug} />
        <Title name={name} />
        <Rating reviews={reviews} />
        <Description description={description}/>
        <Images images={images} />
        <Reviews reviews={reviews}/>   
      </div>
      <ReservationCard openTime={open_time} closeTime={close_time} />
    </>
  )
}

export default RestaurantDetailsPage;